package com.mayokunadeniyi.instantweather.kaspresso

const val BEFORE = "BEFORE:"
const val EXPECTED = "EXPECTED:"
const val SCREENSHOT = "SCREENSHOT:"
const val SCREENSHOT_CONTENT = "SCREENSHOT CONTENT:"
const val SCREENSHOT_EXPECTED = "SCREENSHOT EXPECTED:"
const val TITLE_SECTION = "TITLE SECTION:"
const val DESCRIPTION_SECTION = "DESCRIPTION SECTION:"
const val PRECONDITIONS_SECTION = "PRECONDITIONS SECTION:"
const val BEFORE_TEST_SECTION = "BEFORE TEST SECTION"
const val TEST_SECTION = "TEST SECTION"
const val TEST_STEP = "TEST STEP:"
const val SECTION_ID = "SECTION_ID:"